UPDATE orders
SET status = 'SHIPPED'
WHERE status IN ('SHIPPED_TO_VIETNAM', 'ARRIVED_IN_VIETNAM', 'OUT_FOR_DELIVERY');

ALTER TABLE orders
DROP CONSTRAINT IF EXISTS orders_status_check;

ALTER TABLE orders
ADD CONSTRAINT orders_status_check CHECK (status IN (
  'PENDING_PURCHASE',
  'PURCHASED',
  'SHIPPED',
  'COMPLETED'
));

ALTER TABLE orders
ALTER COLUMN status SET DEFAULT 'PENDING_PURCHASE';
